### ISSUE TITLE
Item.mp3 text2speak voice selection

### ISSUE THREAD

**Issue by pilosel** [jersou/studio-pack-generator#4]
The default voice used to convert item test is in English despite the language selection e.g. Studio-Pack-Generator>studio-pack-generator-x86_64-windows.exe -l fr +URL
for instance: [Pourquoi la planète Mars est-elle rouge.item.mp3.zip](https://github.com/jersou/studio-pack-generator/files/7776081/Pourquoi.la.planete.Mars.est-elle.rouge.item.mp3.zip)

**Comment by jersou** [comment]
Hello,
the voice synthesis used is the one of Windows, you have to configure Windows to use the right language.
Otherwise, if you feel able, you can install WSL and picoTTS, studio-pack-generator will use it if it detects it. To install WSL and picoTTS : 

- https://docs.microsoft.com/fr-fr/windows/wsl/install
- https://github.com/jersou/studio-pack-generator/blob/43c7ed2a83c3b25038130248866302eb93c1c3e9/README.md#optional-dependencies

**Comment by jersou** [comment]
I close this issue, the -l option is used for pico2wave usage only. If you don't have WSL+pico2wave on your system, the TTS Windows service will be used with the default configuration. I guess you just have to set your system to the right language
